// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitToken(arg1) {
  return window['go']['main']['App']['EmitToken'](arg1);
}

export function GetAvailableModes() {
  return window['go']['main']['App']['GetAvailableModes']();
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function RunAgentLoop(arg1, arg2) {
  return window['go']['main']['App']['RunAgentLoop'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function WipeMemory() {
  return window['go']['main']['App']['WipeMemory']();
}
