// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAgentLoop(arg1, arg2) {
  return window['go']['main']['App']['CancelAgentLoop'](arg1, arg2);
}

export function CreateConversation(arg1) {
  return window['go']['main']['App']['CreateConversation'](arg1);
}

export function GetAvailableModes() {
  return window['go']['main']['App']['GetAvailableModes']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversations() {
  return window['go']['main']['App']['GetConversations']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function GetRuntimeStatus() {
  return window['go']['main']['App']['GetRuntimeStatus']();
}

export function RunAgentLoop(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunAgentLoop'](arg1, arg2, arg3);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['main']['App']['SetMode'](arg1);
}

export function WipeMemory() {
  return window['go']['main']['App']['WipeMemory']();
}
