// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelAgentLoop(arg1:string,arg2:string):Promise<void>;

export function CreateConversation(arg1:string):Promise<Record<string, any>>;

export function GetAvailableModes():Promise<Array<string>>;

export function GetConversation(arg1:string):Promise<Record<string, any>>;

export function GetConversations():Promise<Array<Record<string, any>>>;

export function GetMode():Promise<string>;

export function GetRuntimeStatus():Promise<Record<string, any>>;

export function RunAgentLoop(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function SendMessage(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SetMode(arg1:string):Promise<void>;

export function WipeMemory():Promise<string>;
