// Type declarations for Wails-generated Go bindings.
// When 'wails dev' runs, it generates these automatically in wailsjs/.
// This file provides types for IDE support before bindings are generated.

export interface AgentResponse {
  content: string;
  tools_used: string[];
  memory_recalled: number;
  latency_ms: number;
}

export interface ConversationSummary {
  id: string;
  title: string;
  message_count: number;
  last_activity: string;
}

// These functions are generated by Wails at runtime.
// In dev mode they are available via the wailsjs/ directory.
// We declare them here so TypeScript doesn't complain before generation.
export declare function SendMessage(
  conversationID: string,
  message: string
): Promise<AgentResponse>;

export declare function GetConversations(): Promise<ConversationSummary[]>;
